name: Daily Manchester Update

on:
  schedule:
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Optional: This line forces the runner to use Node 24 immediately
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v6  # Updated from v4

      - name: Set up Python
        uses: actions/setup-python@v6 # Updated from v4
        with:
         python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: | 
             python manchester_deals.py
             echo "Waiting 60 seconds to avoid 429 Rate Limit..."
             sleep 60
             python US_Market_News.py
